"""Built-in tools, one module each, read by the router and the reply prompt.

A tool here is something the model can choose for a turn: its row (name,
label, router description, argument schema, waiting lines) and its parser
from a tool call to a typed action. Adding a tool is adding a module and a
line in `registry.py`; nothing else changes. Skills - instruction packs the
model invokes by meaning - live in `backend/skills/` and are offered to the
same router alongside these.
"""

from .actions import (
    CreateDiagramAction,
    CreateDocumentAction,
    DelegateAction,
    DiscussImageAction,
    EditDocumentAction,
    EditImageAction,
    GenerateImageAction,
    MainAction,
    ManageCheckInsAction,
    ManageRunsAction,
    ManageSkillsAction,
    ManageTasksAction,
    RecallHistoryAction,
    SaveSkillAction,
    ScheduleTaskAction,
    ScoutScheduleAction,
    SearchAction,
    SendEventLinksAction,
    ShowImageAction,
    ToolboxAction,
    UseSkillAction,
)
from .base import BuiltinTool
from .contracts import EffectContract
from .registry import (
    AUTOMATION_TOOLS,
    DRAFT_WITHHELD,
    NOT_BUILTIN,
    SEARCH_CAPABILITY,
    SEARCH_CREDITS_CAPABILITY,
    SEARCH_CREDITS_TOOL,
    SEARCH_TOOL,
    UNATTENDED_WITHHELD,
    WEATHER_CAPABILITY,
    WEATHER_TOOL,
    action_creates,
    action_key,
    builtin_tools,
    contract_for_action,
    describe_action,
    later_step_tools,
    parse_builtin,
    tool_name_of,
    waiting_line,
)

__all__ = [
    "AUTOMATION_TOOLS",
    "DRAFT_WITHHELD",
    "UNATTENDED_WITHHELD",
    "NOT_BUILTIN",
    "SEARCH_CAPABILITY",
    "SEARCH_TOOL",
    "WEATHER_CAPABILITY",
    "SEARCH_CREDITS_CAPABILITY",
    "SEARCH_CREDITS_TOOL",
    "WEATHER_TOOL",
    "BuiltinTool",
    "EffectContract",
    "action_creates",
    "action_key",
    "contract_for_action",
    "later_step_tools",
    "tool_name_of",
    "CreateDiagramAction",
    "CreateDocumentAction",
    "EditDocumentAction",
    "DelegateAction",
    "DiscussImageAction",
    "EditImageAction",
    "GenerateImageAction",
    "MainAction",
    "ManageSkillsAction",
    "ManageTasksAction",
    "ManageCheckInsAction",
    "ManageRunsAction",
    "ScoutScheduleAction",
    "SendEventLinksAction",
    "RecallHistoryAction",
    "SaveSkillAction",
    "ScheduleTaskAction",
    "SearchAction",
    "ShowImageAction",
    "ToolboxAction",
    "UseSkillAction",
    "builtin_tools",
    "describe_action",
    "parse_builtin",
    "waiting_line",
]
